version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # LocalStack Gateway (all services)
      - "4510-4559:4510-4559" # service ports
    environment:
      - SERVICES=dynamodb,s3,stepfunctions,cloudwatch,sts,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
    volumes:
      # - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
